# fly.toml app configuration file generated for financial-calculator on 2023-09-23T21:52:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "financial-calculator"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
